// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "fastmlm_types.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// C_fastmlm_create
SEXP C_fastmlm_create(Eigen::Map<Eigen::VectorXd> y, Eigen::Map<Eigen::MatrixXd> X, Eigen::MappedSparseMatrix<double> Zt, Eigen::MappedSparseMatrix<double> Lambdat, Eigen::Map<Eigen::VectorXi> Lind, Eigen::Map<Eigen::VectorXd> lower, bool REML);
RcppExport SEXP _fastmlm_C_fastmlm_create(SEXP ySEXP, SEXP XSEXP, SEXP ZtSEXP, SEXP LambdatSEXP, SEXP LindSEXP, SEXP lowerSEXP, SEXP REMLSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::MappedSparseMatrix<double> >::type Zt(ZtSEXP);
    Rcpp::traits::input_parameter< Eigen::MappedSparseMatrix<double> >::type Lambdat(LambdatSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXi> >::type Lind(LindSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< bool >::type REML(REMLSEXP);
    rcpp_result_gen = Rcpp::wrap(C_fastmlm_create(y, X, Zt, Lambdat, Lind, lower, REML));
    return rcpp_result_gen;
END_RCPP
}
// C_fastmlm_deviance
double C_fastmlm_deviance(SEXP xptr, Eigen::Map<Eigen::VectorXd> theta);
RcppExport SEXP _fastmlm_C_fastmlm_deviance(SEXP xptrSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xptr(xptrSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(C_fastmlm_deviance(xptr, theta));
    return rcpp_result_gen;
END_RCPP
}
// C_fastmlm_result
Rcpp::List C_fastmlm_result(SEXP xptr);
RcppExport SEXP _fastmlm_C_fastmlm_result(SEXP xptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type xptr(xptrSEXP);
    rcpp_result_gen = Rcpp::wrap(C_fastmlm_result(xptr));
    return rcpp_result_gen;
END_RCPP
}
// C_fastmlm_fit
Rcpp::List C_fastmlm_fit(Eigen::Map<Eigen::VectorXd> y, Eigen::Map<Eigen::MatrixXd> X, Eigen::MappedSparseMatrix<double> Zt, Eigen::MappedSparseMatrix<double> Lambdat, Eigen::Map<Eigen::VectorXi> Lind, Eigen::Map<Eigen::VectorXd> theta_start, Eigen::Map<Eigen::VectorXd> lower, Eigen::Map<Eigen::VectorXi> Gp, bool REML, int maxiter, double ftol, double gtol, int pcg_threshold, int verbose);
RcppExport SEXP _fastmlm_C_fastmlm_fit(SEXP ySEXP, SEXP XSEXP, SEXP ZtSEXP, SEXP LambdatSEXP, SEXP LindSEXP, SEXP theta_startSEXP, SEXP lowerSEXP, SEXP GpSEXP, SEXP REMLSEXP, SEXP maxiterSEXP, SEXP ftolSEXP, SEXP gtolSEXP, SEXP pcg_thresholdSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::MappedSparseMatrix<double> >::type Zt(ZtSEXP);
    Rcpp::traits::input_parameter< Eigen::MappedSparseMatrix<double> >::type Lambdat(LambdatSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXi> >::type Lind(LindSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type theta_start(theta_startSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXi> >::type Gp(GpSEXP);
    Rcpp::traits::input_parameter< bool >::type REML(REMLSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type ftol(ftolSEXP);
    Rcpp::traits::input_parameter< double >::type gtol(gtolSEXP);
    Rcpp::traits::input_parameter< int >::type pcg_threshold(pcg_thresholdSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(C_fastmlm_fit(y, X, Zt, Lambdat, Lind, theta_start, lower, Gp, REML, maxiter, ftol, gtol, pcg_threshold, verbose));
    return rcpp_result_gen;
END_RCPP
}
// C_fastmlm_fit_glmm
Rcpp::List C_fastmlm_fit_glmm(Eigen::Map<Eigen::VectorXd> y, Eigen::Map<Eigen::MatrixXd> X, Eigen::MappedSparseMatrix<double> Zt, Eigen::MappedSparseMatrix<double> Lambdat, Eigen::Map<Eigen::VectorXi> Lind, Eigen::Map<Eigen::VectorXd> theta_start, Eigen::Map<Eigen::VectorXd> lower, Eigen::Map<Eigen::VectorXi> Gp, Eigen::Map<Eigen::VectorXd> prior_weights, std::string family_str, std::string link_str, int maxiter, double ftol, double gtol, int verbose);
RcppExport SEXP _fastmlm_C_fastmlm_fit_glmm(SEXP ySEXP, SEXP XSEXP, SEXP ZtSEXP, SEXP LambdatSEXP, SEXP LindSEXP, SEXP theta_startSEXP, SEXP lowerSEXP, SEXP GpSEXP, SEXP prior_weightsSEXP, SEXP family_strSEXP, SEXP link_strSEXP, SEXP maxiterSEXP, SEXP ftolSEXP, SEXP gtolSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::MappedSparseMatrix<double> >::type Zt(ZtSEXP);
    Rcpp::traits::input_parameter< Eigen::MappedSparseMatrix<double> >::type Lambdat(LambdatSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXi> >::type Lind(LindSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type theta_start(theta_startSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXi> >::type Gp(GpSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd> >::type prior_weights(prior_weightsSEXP);
    Rcpp::traits::input_parameter< std::string >::type family_str(family_strSEXP);
    Rcpp::traits::input_parameter< std::string >::type link_str(link_strSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type ftol(ftolSEXP);
    Rcpp::traits::input_parameter< double >::type gtol(gtolSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(C_fastmlm_fit_glmm(y, X, Zt, Lambdat, Lind, theta_start, lower, Gp, prior_weights, family_str, link_str, maxiter, ftol, gtol, verbose));
    return rcpp_result_gen;
END_RCPP
}
// C_fastmlm_blas_info
Rcpp::List C_fastmlm_blas_info();
RcppExport SEXP _fastmlm_C_fastmlm_blas_info() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(C_fastmlm_blas_info());
    return rcpp_result_gen;
END_RCPP
}
// C_fastmlm_set_threads
void C_fastmlm_set_threads(int blas_threads, int omp_threads);
RcppExport SEXP _fastmlm_C_fastmlm_set_threads(SEXP blas_threadsSEXP, SEXP omp_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type blas_threads(blas_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type omp_threads(omp_threadsSEXP);
    C_fastmlm_set_threads(blas_threads, omp_threads);
    return R_NilValue;
END_RCPP
}
// C_fastmlm_benchmark_blas
double C_fastmlm_benchmark_blas(int n);
RcppExport SEXP _fastmlm_C_fastmlm_benchmark_blas(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(C_fastmlm_benchmark_blas(n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastmlm_C_fastmlm_create", (DL_FUNC) &_fastmlm_C_fastmlm_create, 7},
    {"_fastmlm_C_fastmlm_deviance", (DL_FUNC) &_fastmlm_C_fastmlm_deviance, 2},
    {"_fastmlm_C_fastmlm_result", (DL_FUNC) &_fastmlm_C_fastmlm_result, 1},
    {"_fastmlm_C_fastmlm_fit", (DL_FUNC) &_fastmlm_C_fastmlm_fit, 14},
    {"_fastmlm_C_fastmlm_fit_glmm", (DL_FUNC) &_fastmlm_C_fastmlm_fit_glmm, 15},
    {"_fastmlm_C_fastmlm_blas_info", (DL_FUNC) &_fastmlm_C_fastmlm_blas_info, 0},
    {"_fastmlm_C_fastmlm_set_threads", (DL_FUNC) &_fastmlm_C_fastmlm_set_threads, 2},
    {"_fastmlm_C_fastmlm_benchmark_blas", (DL_FUNC) &_fastmlm_C_fastmlm_benchmark_blas, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastmlm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
