# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_fastmlm_create <- function(y, X, Zt, Lambdat, Lind, lower, REML) {
    .Call(`_fastmlm_C_fastmlm_create`, y, X, Zt, Lambdat, Lind, lower, REML)
}

C_fastmlm_deviance <- function(xptr, theta) {
    .Call(`_fastmlm_C_fastmlm_deviance`, xptr, theta)
}

C_fastmlm_result <- function(xptr) {
    .Call(`_fastmlm_C_fastmlm_result`, xptr)
}

C_fastmlm_fit <- function(y, X, Zt, Lambdat, Lind, theta_start, lower, Gp, REML, maxiter, ftol, gtol, pcg_threshold, verbose) {
    .Call(`_fastmlm_C_fastmlm_fit`, y, X, Zt, Lambdat, Lind, theta_start, lower, Gp, REML, maxiter, ftol, gtol, pcg_threshold, verbose)
}

C_fastmlm_blas_info <- function() {
    .Call(`_fastmlm_C_fastmlm_blas_info`)
}

C_fastmlm_set_threads <- function(blas_threads, omp_threads) {
    invisible(.Call(`_fastmlm_C_fastmlm_set_threads`, blas_threads, omp_threads))
}

C_fastmlm_benchmark_blas <- function(n) {
    .Call(`_fastmlm_C_fastmlm_benchmark_blas`, n)
}

